# Generated by Django 5.1.3 on 2024-11-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="dni",
            field=models.IntegerField(unique=True),
        ),
    ]
