# Generated by Django 5.1.3 on 2024-11-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bicicleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EXCELENTE", "Excelente"),
                            ("BUENO", "Bueno"),
                            ("MALO", "Malo"),
                            ("ROTA", "Rota"),
                        ],
                        default="EXCELENTE",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
