# Generated by Django 5.1.3 on 2024-11-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bicicletas", "0001_initial"),
        ("estacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bicicleta",
            name="estacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bicicletas",
                to="estacion.estacion",
            ),
        ),
    ]
