# Generated by Django 5.1.3 on 2024-11-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viajes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viaje",
            name="estado_final",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXCELENTE", "Excelente"),
                    ("BUENO", "Bueno"),
                    ("MALO", "Malo"),
                    ("ROTA", "Rota"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
