# Generated by Django 5.1.3 on 2024-11-09 21:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("viajes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("costo", models.FloatField()),
                ("descripcion", models.TextField()),
                (
                    "viaje",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multa",
                        to="viajes.viaje",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacidad",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "posicion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estacion.ubicacion",
                    ),
                ),
            ],
        ),
    ]
